<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MatchingFrontier • MatchingFrontier</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="MatchingFrontier">
<meta property="og:description" content="MatchingFrontier">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">MatchingFrontier</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">4.0.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/MatchingFrontier.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="MatchingFrontier_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>MatchingFrontier</h1>
                        <h4 class="author">Noah Greifer</h4>
            
            <h4 class="date">2021-10-29</h4>
      
      
      <div class="hidden name"><code>MatchingFrontier.Rmd</code></div>

    </div>

    
    
<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>Matching methods have become extremely popular among researchers working with observational data, especially when used as a nonparametric preprocessing step to reduce model dependence. But despite this popularity, existing matching approaches leave researchers with two fundamental tensions. First, they are often designed to maximize one metric (such as propensity score or Mahalanobis distance) but are judged against another for which they were not designed (such as the <span class="math inline">\(L_1\)</span> statistic or differences in means). Second, they lack a principled solution to revealing the implicit bias-variance trade off: matching methods need to optimize with respect to both imbalance (between the treated and control groups) and the number of observations pruned, but existing approaches optimize with respect to only one; users then either ignore the second or tweak it without a formal stopping rule.</p>
<p><code>MatchingFrontier</code> resolves both tensions by consolidating previous techniques into a single, optimal, and flexible approach. The software calculates the matching solution with maximum balance for each possible sample size (<span class="math inline">\(N\)</span>, <span class="math inline">\(N-1\)</span>, <span class="math inline">\(N-2\)</span>, …) and returns each solution, the whole of which constitute the frontier, from which the user can easily choose one, several, or all subsamples with which to conduct the final analysis, given their own choice of imbalance metric and quantity of interest. <code>MatchingFrontier</code> solves the joint optimization problem in one run, automatically, without manual tweaking, and without iteration. Although for each subset size <span class="math inline">\(k\)</span>, there exist a huge number of unique subsets (<span class="math inline">\(N \choose k\)</span>), <code>MatchingFrontier</code> includes specially designed and extremely fast algorithms that give the optimal answer, usually in a few minutes or less.</p>
</div>
<div id="general-framework" class="section level2">
<h2 class="hasAnchor">
<a href="#general-framework" class="anchor"></a>General Framework</h2>
<p>Matching methods are designed to reduce imbalance in data by selectively pruning and optionally pairing observations, which in turn reduces model dependence. However, pruning reduces sample size and therefore may increase variance in the eventual estimates. Users of matching are then confronted with the perennial bias-variance trade-off. Perhaps surprisingly, existing approaches to matching do not conduct the implied joint optimization of bias and variance. Rather, they improve one dimension of the optimization and leave the second to the user. Such an approach is time consuming and rarely yields the optimal solution. <span class="citation">King, Lucas, and Nielsen (<a href="#ref-king2017" role="doc-biblioref">2017</a>)</span> proposes a solution to this joint optimization, which is implemented in <code>MatchingFrontier</code>. We point users of <code>MatchingFrontier</code> to <span class="citation">King, Lucas, and Nielsen (<a href="#ref-king2017" role="doc-biblioref">2017</a>)</span> for algorithmic details and theoretical proofs.</p>
<p>Frontiers depend on the imbalance metric used. <code>MatchingFrontier</code> includes the average Mahlanobis metric and L1 statistic described in <span class="citation">King, Lucas, and Nielsen (<a href="#ref-king2017" role="doc-biblioref">2017</a>)</span>, as well as a more recently developed metric known as the energy distance, developed by <span class="citation">Székely and Rizzo (<a href="#ref-sz%C3%A9kely2013" role="doc-biblioref">2013</a>)</span> and described by <span class="citation">Huling and Mak (<a href="#ref-huling2020" role="doc-biblioref">2020</a>)</span> for use in comparing distributions in observational studies. Other metrics are available as well, creating three classes of frontiers that correspond to a given imbalance metric and matching method; these include pair distance-based frontiers, bin-based frontiers, and energy distance-based frontiers.</p>
<p>Estimated effects generalize to different target samples depending on how the matching is performed. In <code>MatchingFrontier</code>, the user can choose the estimand, i.e., the effect corresponding to the group to which the effect is meant to generalize, from among the following choices:</p>
<ul>
<li><p>The sample average treatment treatment effect (SATE), the average effect of treatment in the entire sample.</p></li>
<li><p>The feasible sample average treatment effect (FSATE), the average effect of treatment in the sample remaining after some units from both groups are dropped.</p></li>
<li><p>The sample average treatment effect in the treated (SATT), the average effect of treatment in the sample of those who were treated.</p></li>
<li><p>The feasible sample average treatment effect in the treated (FSATT), the average effect of treatment in the sample of treated units after some treated units are dropped.</p></li>
</ul>
<p>Choosing between SATE and SATT will depend on the research question of interest; see <span class="citation">Greifer and Stuart (<a href="#ref-greifer2021" role="doc-biblioref">2021</a>)</span> for guidance on making this choice. When estimating these effects would require extrapolation, e.g., because of poor overlap between the treatment groups, their “feasible” versions might be considered instead <span class="citation">(King, Lucas, and Nielsen <a href="#ref-king2017" role="doc-biblioref">2017</a>; Iacus, King, and Porro <a href="#ref-iacus2019" role="doc-biblioref">2019</a>)</span>, which correspond to the effect of treatment for an overlap sample not specified prior to the analysis.</p>
<p>Below, we describe the different frontiers available and which quantities of interest (i.e., estimand) each can target.</p>
<div id="pair-distance-based-frontiers" class="section level3">
<h3 class="hasAnchor">
<a href="#pair-distance-based-frontiers" class="anchor"></a>Pair distance-based frontiers</h3>
<p>Pair distance-based frontiers involve a first step of pairing observations based on the distances between them (i.e., using 1:1 matching), and the frontier is formed by discarding one pair at a time until none remain, similar to applying a tighter and tighter caliper. The imbalance metric is the average of the pairwise distances of the remaining units. When pair distance-based metrics are equal to zero, the remaining units comprise pairs of units identical on the included covariates. Pairing is done with replacement, so each unit can be used as a pair to multiple other units. The distance between units used to form the pairs and compute the imbalance metric can be computed as the Mahalanobis distance, the Euclidean distance, or a user-supplied distance.</p>
<p>These frontiers can only be used when the quantity of interest is the FSATE or FSATT. For the FSATE, each treated unit is paired with a control unit, and each control unit is paired with a treated unit; these processes are independent so a control unit may not be paired with the treated unit it is paired to. Each pair can be thought of as a single-headed arrow pointing from the focal unit to its paired unit; pairs are not bi-directional (except by chance). The effect estimated after the initial match (prior to dropping any units) corresponds to the SATE; once any units are dropped, the estimand corresponds to the FSATE. For the FSATT, each treated unit is paired with a control unit (i.e., arrows emanate from treated units but not from control units), and the frontier is formed by dropping treated units. The effect estimated after the initial match (prior to dropping any units) corresponds to the SATT; once any units are dropped, the estimand corresponds to the FSATT.</p>
</div>
<div id="bin-based-frontiers" class="section level3">
<h3 class="hasAnchor">
<a href="#bin-based-frontiers" class="anchor"></a>Bin-based frontiers</h3>
<p>Bin-based frontiers involve assigning units into bins based on the unique combination of their coarsened covariates. The frontier is formed by dropping one unit at a time, in particular, the unit that when dropped would yield the greatest decrease in the imbalance metric. Unlike pair distance-based frontiers, bin-based frontiers are formed by subset selection rather than pairing; units are not paired with each other, and the initial point of the frontier is computed on the unmodified sample (in contrast to pair distance-based frontiers, where the initial point is computed after pairing). Bin-based frontiers can be thought of as a close relative to coarsened exact matching <span class="citation">(Iacus, King, and Porro <a href="#ref-iacus2012" role="doc-biblioref">2012</a>)</span>, as implemented in the <code>cem</code> and in <code>MatchIt</code> packages (i.e., using <code><a href="https://kosukeimai.github.io/MatchIt/reference/matchit.html">matchit()</a></code> with <code>method = "cem"</code>). (In general, it makes more sense to perform coarsened exact matching than to create a bin-based frontier because all points along the frontier will have worse balance than the result of a coarsened exact match <span class="citation">(King, Lucas, and Nielsen <a href="#ref-king2017" role="doc-biblioref">2017</a>)</span>; bin-based frontiers are provided here largely for comparison purposes.)</p>
<p>The available imbalance metrics for bin-based frontiers include the <span class="math inline">\(L_1\)</span> and <span class="math inline">\(L_2\)</span> statistics, which summarize the discrepancy between the relative proportions of treated and control units in each bin <span class="citation">(King, Lucas, and Nielsen <a href="#ref-king2017" role="doc-biblioref">2017</a>)</span> and are computed as</p>
<p><span class="math display">\[
L_1(H)=\frac{1}{2}\sum_{(\ell_1\dots\ell_k)\in H}{|f_{\ell_1\dots\ell_k}-g_{\ell_1\dots\ell_k}|}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
L_2(H)=\frac{1}{2}\sqrt{\sum_{(\ell_1\dots\ell_k)\in H}{(f_{\ell_1\dots\ell_k}-g_{\ell_1\dots\ell_k})^2}}
\]</span></p>
<p>where <span class="math inline">\(H\)</span> is a vector of the number of bins for the covariates, <span class="math inline">\(\ell_1 \dots\ell_k\)</span> are the strata formed by applying the bin boundaries to the covariates, and <span class="math inline">\(f_{\ell_1 \dots\ell_k}\)</span> and <span class="math inline">\(g_{\ell_1 \dots\ell_k}\)</span> are the proportion of treated and control units, respectively, in each stratum. The number of bins to use for each covariate can be chosen by the user or computed automatically as the number of bins that yield the median value of the imbalance metric across a random sample of binnings in the full sample, thereby removing the dependence of the frontier on a specific choice by the user <span class="citation">(Iacus, King, and Porro <a href="#ref-iacus2011" role="doc-biblioref">2011</a>)</span>.</p>
<p>These frontiers can be used when the quantity of interest is the FSATE or SATT. For the FSATE, units are dropped one at a time. Units will be dropped from the bins with the largest treatment group imbalance (i.e., so units with no members of the other bin will be dropped first). For the SATT, only control units can be dropped; all treated units will remain, even if no controls units share a bin with them.</p>
</div>
<div id="energy-distance-based-frontiers" class="section level3">
<h3 class="hasAnchor">
<a href="#energy-distance-based-frontiers" class="anchor"></a>Energy distance-based frontiers</h3>
<p>Like bin-based frontiers, energy distance-based frontiers involve subset selection rather than pairing. The frontier is formed by dropping one unit at a time, in particular, the unit that when dropped would yield the greatest decrease in the imbalance metric. The imbalance metric is the energy distance, a scalar measure of the difference between two multivariate cumulative density functions <span class="citation">(Rizzo and Székely <a href="#ref-rizzo2016" role="doc-biblioref">2016</a>; Székely and Rizzo <a href="#ref-sz%C3%A9kely2013" role="doc-biblioref">2013</a>)</span>, computed as: <span class="math display">\[
\mathcal{E}(\mathbf{X}_1,\mathbf{X}_2) = 2 D_{12} -  D_{11} -  D_{22}
\]</span> where</p>
<p><span class="math display">\[\begin{align}
D_{12}&amp;=\frac{1}{N_1 N_2}\sum_{i \in \mathcal{X}_1}{\sum_{j \in \mathcal{X}_2}{||X_{1i}-X_{2j}||_2}} \\ D_{11} &amp;= \frac{1}{N_1^2}\sum_{i \in \mathcal{X}_1}{\sum_{i' \in \mathcal{X}_1}{||X_{1i}-X_{1i'}||_2}} \\ D_{22} &amp;= \frac{1}{N_2^2}\sum_{j \in \mathcal{X}_2}{\sum_{j' \in \mathcal{X}_2}{||X_{2j}-X_{2j'}||_2}}
\end{align}\]</span></p>
<p>and where <span class="math inline">\(\mathcal{X}_1\)</span> and <span class="math inline">\(\mathcal{X}_2\)</span> are two samples of size <span class="math inline">\(N_1\)</span> and <span class="math inline">\(N_2\)</span> of (scaled) variables <span class="math inline">\(\mathbf{X}_1\)</span> and <span class="math inline">\(\mathbf{X}_2\)</span>, respectively, and <span class="math inline">\(||.||_2\)</span> is the <span class="math inline">\(L_2\)</span>-norm (i.e., Euclidean distance). At each point on the frontier, each unit’s contribution to the energy distance is computed as the difference between the energy distance with them included and that with them dropped, and the unit with the greatest contribution is dropped. Energy-distance based frontiers can be thought of as a greedy, nonsmooth version of Huling and Mak’s <span class="citation">(<a href="#ref-huling2020" role="doc-biblioref">2020</a>)</span> energy balancing, which estimates weights that directly minimize the energy distance in the weighted sample. The energy distance-based frontier can be useful when weights other than 0 or 1 are undesirable or the optimization required for energy balancing is intractable. Unlike pair distance-based frontiers, the energy distance-based frontier is non-monotonic; there is often a point when discarding additional units increases rather than decreases the imbalance metric, a phenomenon related to the propensity score paradox described in <span class="citation">King and Nielsen (<a href="#ref-king2019" role="doc-biblioref">2019</a>)</span>.</p>
<p>Energy distance-based frontiers can be used when the quantity of interest is the SATE, FSATE, or SATT, making them highly versatile. For the SATE, the energy distance is computed as Huling and Mak’s <span class="citation">(<a href="#ref-huling2020" role="doc-biblioref">2020</a>)</span> “improved” energy distance, which is the sum of the energy distance between the treated group and the original full sample, the energy distance between the control group and the full sample, and the energy distance between the treated and control groups. Units from either group may be dropped. As the energy distance decreases, the resulting groups each increasingly resemble the full sample and each other. For the FSATE and SATT, the energy distance is computed only between the treated and control groups (ignoring the distance from the full sample), and for the SATT, only control units can be dropped.</p>
</div>
</div>
<div id="using-matchingfrontier" class="section level2">
<h2 class="hasAnchor">
<a href="#using-matchingfrontier" class="anchor"></a>Using <code>MatchingFrontier</code>
</h2>
<p>Here, we provide a basic guide on using <code>MatchingFrontier</code> to compute a balance-sample size frontier. We will use Lalonde’s <span class="citation">(<a href="#ref-lalonde1986" role="doc-biblioref">1986</a>)</span> data on the evaluation of the National Supported Work program to demonstrate <code>MatchingFrontier</code>’s capabilities. This dataset is stored in the <code>MatchIt</code> package <span class="citation">(Ho et al. <a href="#ref-JSSv042i08" role="doc-biblioref">2011</a>)</span>, which is automatically installed alongside <code>MatchingFrontier</code>.</p>
<p>First, we load <code>MatchingFrontier</code> and the <code>lalonde</code> dataset from <code>MatchIt</code>.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://projects.iq.harvard.edu/frontier">"MatchingFrontier"</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"lalonde"</span>, package <span class="op">=</span> <span class="st">"MatchIt"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">lalonde</span><span class="op">)</span></code></pre></div>
<pre><code>##      treat age educ   race married nodegree re74 re75       re78
## NSW1     1  37   11  black       1        1    0    0  9930.0460
## NSW2     1  22    9 hispan       0        1    0    0  3595.8940
## NSW3     1  30   12  black       0        0    0    0 24909.4500
## NSW4     1  27   11  black       0        1    0    0  7506.1460
## NSW5     1  33    8  black       0        1    0    0   289.7899
## NSW6     1  22    9  black       0        1    0    0  4056.4940</code></pre>
<p>The statistical quantity of interest is the causal effect of the treatment (<code>treat</code>) on 1978 earnings (<code>re78</code>). The other variables are pre-treatment covariates. See <code><a href="https://kosukeimai.github.io/MatchIt/reference/lalonde.html">help("lalonde", package = "MatchIt")</a></code> for more information on this dataset. Though the original focus with this dataset was to estimate the average treatment effect in the treated, which corresponded to the effect estimated in the accompanying randomized trial, here we will consider this and other quantities of interest.</p>
<p>The typical workflow for using <code>Matchingfrontier</code> is the following. First, the user computes the balance-sample size frontier corresponding to the chosen quantity of interest (i.e., estimand) and imbalance metric; then, the frontier is visualized in a plot. The user can then estimate treatment effects at each point along the frontier or choose a single point on the frontier on which to estimate the effect.</p>
<div id="computing-the-frontier" class="section level3">
<h3 class="hasAnchor">
<a href="#computing-the-frontier" class="anchor"></a>Computing the frontier</h3>
<p>We start by selecting the quantity of interest and imbalance metric. For now, we will consider the FSATT. Several imbalance metrics can be used with this estimand; here, we use the average Mahalanobis imbalance. Below, we call <code><a href="../reference/makeFrontier.html">makeFrontier()</a></code> with the desired arguments.</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mahal.frontier</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/makeFrontier.html">makeFrontier</a></span><span class="op">(</span><span class="va">treat</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span>
                                 <span class="va">nodegree</span> <span class="op">+</span> <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,
                               data <span class="op">=</span> <span class="va">lalonde</span>, 
                               QOI <span class="op">=</span> <span class="st">"FSATT"</span>, 
                               metric <span class="op">=</span> <span class="st">"Mahal"</span><span class="op">)</span></code></pre></div>
<p>There are a few ways to specify the arguments to <code><a href="../reference/makeFrontier.html">makeFrontier()</a></code>; see <code><a href="../reference/makeFrontier.html">help("makeFrontier")</a></code> for details. Here, we used the formula interface, which requires a model formula of the form <code>A ~ X1 + X2 + ...</code> where <code>A</code> corresponds to the treatment and <code>X1</code> and <code>X2</code> are the pretreatment covariates. We must also supply a dataset to the <code>data</code> argument. Note that no model is being fit here; the model formula serves to indicate which variable is the treatment and which are the covariates. The <code>QOI</code> (i.e., quantity of interest) argument corresponds to the desired estimand; here, we select the FSATT, but others are available depending on the type of frontier, as described previously. The <code>metric</code> argument corresponds to the imbalance metric used. Here, we entered <code>"Mahal"</code> to request the average Mahalanobis imbalance be used.</p>
<p>The frontier is stored in the <code>matchFrontier</code> object, which we have called <code>mahal.frontier</code>. Printing <code>mahal.frontier</code> provides a summary of the type of frontier and its components:</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mahal.frontier</span></code></pre></div>
<pre><code>## A matchFrontier object
## - quantity of interest: FSATT
## - imbalance metric: average pairwise Mahalanobis distance
## - treatment: treat
## - covariates: age, educ, race, married, nodegree, re74, re75
## - number of points: 137</code></pre>
</div>
<div id="plotting-the-frontier" class="section level3">
<h3 class="hasAnchor">
<a href="#plotting-the-frontier" class="anchor"></a>Plotting the frontier</h3>
<p>Now that we have computed the frontier, we plot the frontier using <code><a href="../reference/plot.matchFrontier.html">plot.matchFrontier()</a></code> to visualize the relationship between the number of units dropped and the imbalance metric.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mahal.frontier</span><span class="op">)</span></code></pre></div>
<p><img src="MatchingFrontier_files/figure-html/unnamed-chunk-4-1.png" width="672"></p>
<p>The plot indicates a monotonic negative relationship between the number of units dropped and the average Mahalanobis imbalance. The lower x-axis corresponds to the number of units dropped, and the upper x-axis corresponds to the number of units remaining. Here these sample sizes refer only to the number of treated units dropped or remaining because our quantity of interest is the FSATT. Control units are not counted in this plot because they will be dropped along the with the treated unit they are paired with.</p>
<p>We can use <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> on the <code>matchFrontier</code> object to reveal information about the beginning and end of the frontier.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mahal.frontier</span><span class="op">)</span></code></pre></div>
<pre><code>## Summary of matchFrontier object:
## 
##       N treated N control N total Statistic
## Start       185               185     0.338
## End          13                13         0
## Best         13                13         0
##               ^</code></pre>
<p>From the plot and summary we can see that the initial average Mahalanobis imbalance after matching but before discarding any units was about .338. After dropping 172 treated units, the imbalance falls to 0 (i.e., indicating that the remaining units are exactly matched on all the covariates). Dropping this many units has left us with only about 13 pairs remaining, which is typically far too few to make valid inferences on. Thus, the ideal sample lies somewhere between the beginning and end of the frontier.</p>
<p>We can also view information about balance for individual covariates using <code><a href="../reference/plot.matchFrontier.html">plot.matchFrontier()</a></code>. To do so, we supply the names of individual covariates to the <code>covs</code> argument of <code><a href="../reference/plot.matchFrontier.html">plot.matchFrontier()</a></code> and set <code>stat = "std-diff"</code> for standardized mean differences, which are useful for continuous covariates, and <code>stat = "diff</code>, and for raw mean differences, which are useful for sets of variables that are on the same scale (like binary covariates).</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#Standardized mean differences for continuous covariates</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mahal.frontier</span>, covs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"age"</span>, <span class="st">"educ"</span>, <span class="st">"re74"</span><span class="op">)</span>,
     stat <span class="op">=</span> <span class="st">"std-diff"</span><span class="op">)</span>

<span class="co">#Raw mean differences for categorical covariates</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mahal.frontier</span>, covs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"nodegree"</span>, <span class="st">"married"</span><span class="op">)</span>,
     stat <span class="op">=</span> <span class="st">"diff"</span><span class="op">)</span></code></pre></div>
<p><img src="MatchingFrontier_files/figure-html/unnamed-chunk-6-1.png" width="672"><img src="MatchingFrontier_files/figure-html/unnamed-chunk-6-2.png" width="672"></p>
<p>Here we can see that after an initial imbalance (the three dots on the left side of each plot), pairing has removed much imbalance immediately even without discarding additional units. However, balance can be improved on some covariates by continuing to drop pairs.</p>
<p>To view (standardized) means for each covariate, which allows us to see how the distribution of covariates in the estimation sample varies across the frontier, we can set <code>stat = "std-mean"</code> for standardized means and <code>stat = "mean"</code> for raw means. Using standardized means allows us to see how the standardized mean difference between the covariates in the estimation sample and the covariates in the target sample varies across the frontier; values close to zero indicate that the estimation sample strongly resembles the target sample. Using raw means allows us to see the actual location of the covariate means across the frontier (though make sure variables are on the same scale if multiple are to be included in the same plot!).</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#Standardized means for continuous covariates</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mahal.frontier</span>, covs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"age"</span>, <span class="st">"educ"</span>, <span class="st">"re74"</span><span class="op">)</span>,
     stat <span class="op">=</span> <span class="st">"std-mean"</span><span class="op">)</span>

<span class="co">#Raw means for categorical covariates</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mahal.frontier</span>, covs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"nodegree"</span>, <span class="st">"married"</span><span class="op">)</span>,
     stat <span class="op">=</span> <span class="st">"mean"</span><span class="op">)</span></code></pre></div>
<p><img src="MatchingFrontier_files/figure-html/unnamed-chunk-7-1.png" width="672"><img src="MatchingFrontier_files/figure-html/unnamed-chunk-7-2.png" width="672"></p>
<p>We can see that for some covariates, the distribution in the remaining sample differs quite greatly from the target sample (i.e., the treated group because our quantity of interest is the FSATT). This is the sacrifice we make by pursuing the FSATT instead of the SATT. Estimates reflect the true SATT only to the extent that the covariate distributions in the remaining sample resemble those in the original treated group.</p>
</div>
<div id="extract-a-dataset-from-the-frontier" class="section level3">
<h3 class="hasAnchor">
<a href="#extract-a-dataset-from-the-frontier" class="anchor"></a>Extract a dataset from the frontier</h3>
<p>We can estimate treatment effects at each point along the frontier or at a single point. First, we’ll demonstrate extracting a single dataset from the frontier and further examining it.</p>
<p><code>MatchingFrontier</code> interfaces with <code>MatchIt</code> to use the balance assessment and reporting capabilities of <code>MatchIt</code> and provide a simple, well-documented workflow for estimating effects after matching. We can use the function <code><a href="../reference/frontier_to_matchit.html">frontier_to_matchit()</a></code> to extract a matching specification at one point on the frontier and turn it into a <code>MatchIt</code> object as if it had resulted from a call to <code><a href="https://kosukeimai.github.io/MatchIt/reference/matchit.html">MatchIt::matchit()</a></code>. We need to select the point along the frontier for which this extraction is desired, and this can be specified either based on the number of units dropped or the number of units remaining. Here, we’ll pick the point on the frontier with 100 units remaining (corresponding to dropping 85 units).</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mahal.matchit</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/frontier_to_matchit.html">frontier_to_matchit</a></span><span class="op">(</span><span class="va">mahal.frontier</span>, N <span class="op">=</span> <span class="fl">100</span><span class="op">)</span>
<span class="co">#same thing:     frontier_to_matchit(mahal.frontier, Ndrop = 85)</span></code></pre></div>
<p>Printing the new <code>matchit</code> object provides some information about it and indicates that it is indeed a <code>matchit</code> object.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mahal.matchit</span></code></pre></div>
<pre><code>## A matchit object
##  - method: An unspecified matching method
##  - number of obs.: 614 (original), 152 (matched)
##  - target estimand: ATT
##  - covariates: age, educ, race, married, nodegree, re74, re75</code></pre>
<p>We can use <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> from <code>MatchIt</code> to assess balance on the covariates individually before and after matching, providing more detail than the original imbalance metric alone:</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mahal.matchit</span>, improvement <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## makeFrontier(formula = treat ~ age + educ + race + married + 
##     nodegree + re74 + re75, data = lalonde, QOI = "FSATT", metric = "Mahal")
## 
## Summary of Balance for All Data:
##            Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean eCDF Max
## age              25.8162       28.0303         -0.3094     0.4400    0.0813   0.1577
## educ             10.3459       10.2354          0.0550     0.4959    0.0347   0.1114
## raceblack         0.8432        0.2028          1.7615          .    0.6404   0.6404
## racehispan        0.0595        0.1422         -0.3498          .    0.0827   0.0827
## racewhite         0.0973        0.6550         -1.8819          .    0.5577   0.5577
## married           0.1892        0.5128         -0.8263          .    0.3236   0.3236
## nodegree          0.7081        0.5967          0.2450          .    0.1114   0.1114
## re74           2095.5737     5619.2365         -0.7211     0.5181    0.2248   0.4470
## re75           1532.0553     2466.4844         -0.2903     0.9563    0.1342   0.2876
## 
## 
## Summary of Balance for Matched Data:
##            Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean eCDF Max Std. Pair Dist.
## age              23.7200       23.6600          0.0084     0.8956    0.0115     0.08          0.1146
## educ             10.3400       10.3400          0.0000     0.9772    0.0000     0.00          0.0000
## raceblack         0.8700        0.3600          1.4028          .    0.5100     0.51          1.6778
## racehispan        0.0600        0.1300         -0.2960          .    0.0700     0.07          0.7189
## racewhite         0.0700        0.5100         -1.4847          .    0.4400     0.44          1.7546
## married           0.1000        0.4600         -0.9192          .    0.3600     0.36          1.1234
## nodegree          0.6700        0.6700          0.0000          .    0.0000     0.00          0.0000
## re74            968.7927     1041.6442         -0.0149     0.9684    0.0192     0.22          0.0553
## re75            446.6006      436.0152          0.0033     0.9875    0.0048     0.03          0.0286
## 
## Sample Sizes:
##               Control Treated
## All            429.       185
## Matched (ESS)   30.67     100
## Matched         52.       100
## Unmatched      377.        85
## Discarded        0.         0</code></pre>
<p>See <code><a href="https://kosukeimai.github.io/MatchIt/reference/summary.matchit.html">help("summary.matchit", package = "MatchIt")</a></code> for more information on <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> and its options. Here we can see the initial imbalance and the imbalance remaining after selecting a point along the frontier. (Note that selecting the first point on the frontier, before dropping any units, still involves pairing the units when using the pair distance-based frontier, so balance at this point will typically not coincide with the balance for the full dataset prior to matching.) Balance in the matched sample is much better for most of the covariates, though the categorical covariates remain imbalanced (this is a known weakness of the Mahalanobis distance for matching <span class="citation">(Rosenbaum <a href="#ref-rosenbaum2020" role="doc-biblioref">2020</a>; Stuart <a href="#ref-stuart2010" role="doc-biblioref">2010</a>)</span>). Finally, at the bottom we can see a summary of the remaining sample sizes. 100 treated units remain, just as we requested. Those 100 treated units are matched to a total of 52 control units because matching is done with replacement in <code>MatchingFrontier</code>. However, the matching weights required to estimate the FSATT only yield an effective sample size (ESS) of approximately 31 for for the control units.</p>
<p>To estimate the treatment effect at this point on the frontier, we can use a regression of the outcome on the treated (and optionally the covariates) in the matched sample. The matched dataset can be extracted in one of two ways: using <code><a href="https://kosukeimai.github.io/MatchIt/reference/match.data.html">match.data()</a></code> or <code><a href="https://kosukeimai.github.io/MatchIt/reference/match.data.html">get_matches()</a></code> on the <code>matchit</code> object, or using <code><a href="../reference/generateDataset.html">generateDataset()</a></code> on the <code>matchFrontier</code> object. Both yield identical results.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mahal.matched.data</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/generateDataset.html">generateDataset</a></span><span class="op">(</span><span class="va">mahal.frontier</span>, N <span class="op">=</span> <span class="fl">100</span><span class="op">)</span>
<span class="co">#Same result:         MatchIt::match.data(mahal.matchit, data = lalonde)</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">mahal.matched.data</span><span class="op">)</span></code></pre></div>
<pre><code>##      treat age educ   race married nodegree re74 re75       re78 weights
## NSW2     1  22    9 hispan       0        1    0    0  3595.8940       1
## NSW3     1  30   12  black       0        0    0    0 24909.4500       1
## NSW4     1  27   11  black       0        1    0    0  7506.1460       1
## NSW5     1  33    8  black       0        1    0    0   289.7899       1
## NSW6     1  22    9  black       0        1    0    0  4056.4940       1
## NSW7     1  23   12  black       0        0    0    0     0.0000       1</code></pre>
<p>The returned dataset contains only the matched units for use in estimating treatment effects. With pair distance-based frontiers, we have the option to set <code>dup = TRUE</code>, which creates a dataset with an entry for every for unit for every time that unit is used in a match. Because several control units are matched to multiple treated units, they will appear more than once in the returned dataset. Setting <code>dup = FALSE</code> (the default) instead requires that each unit appears no more than once in the returned dataset, with weights present to reflect the reuse of units, but information about pair membership will be lost; this is equivalent to using <code><a href="https://kosukeimai.github.io/MatchIt/reference/match.data.html">MatchIt::match.data()</a></code> on the returned <code>matchit</code> object. See <code><a href="../reference/generateDataset.html">help("generateDataset")</a></code> for more details.</p>
</div>
<div id="estimating-treatment-effects-and-assessing-model-sensitivity" class="section level3">
<h3 class="hasAnchor">
<a href="#estimating-treatment-effects-and-assessing-model-sensitivity" class="anchor"></a>Estimating treatment effects and assessing model sensitivity</h3>
<p>We can use regression to estimate the treatment effect in the matched sample. See <code><a href="https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html">vignette("estimating-effects", package = "MatchIt")</a></code> for more details on estimating treatment effects after matching with replacement. Here we use a linear regression adjusting for the matched covariates. We must include use the matching weights in the regression and use robust standard errors to account for the weights <span class="citation">(Hill and Reiter <a href="#ref-hill2006" role="doc-biblioref">2006</a>)</span>.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"lmtest"</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://sandwich.R-Forge.R-project.org/">"sandwich"</a></span><span class="op">)</span>

<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">re78</span> <span class="op">~</span> <span class="va">treat</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span>
            <span class="va">nodegree</span> <span class="op">+</span> <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,
          data <span class="op">=</span> <span class="va">mahal.matched.data</span>, weights <span class="op">=</span> <span class="va">weights</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/coeftest.html">coeftest</a></span><span class="op">(</span><span class="va">fit</span>, vcov. <span class="op">=</span> <span class="va">vcovHC</span><span class="op">)</span><span class="op">[</span><span class="st">"treat"</span>,, drop <span class="op">=</span> <span class="cn">FALSE</span><span class="op">]</span></code></pre></div>
<pre><code>##       Estimate Std. Error    t value  Pr(&gt;|t|)
## treat 90.13604   1615.437 0.05579669 0.9555822</code></pre>
<p>We chose a specific outcome model, but we could have chosen others, e.g., by including powers of covariates or interactions between them. We can assess how dependent on our choice of model our results are using the <code><a href="../reference/modelDependence.html">modelDependence()</a></code> function in <code>MatchingFrontier</code>. The output of <code><a href="../reference/modelDependence.html">modelDependence()</a></code> is a pair of bounds representing the treatment effects possible from specifying many possible models. Narrow bounds indicate that our results are not sensitive to our choice of model, which is a good thing because it implies our conclusions are not simply the result of fishing for a desired outcome. See also the <code>ExtremeBounds</code> package <span class="citation">(Hlavac <a href="#ref-hlavac2016" role="doc-biblioref">2016</a>)</span>, which provides greater functionality focused on variable selection.</p>
<p><code>MatchingFrontier</code> has two methods of assessing model dependence: the extreme bounds procedure <span class="citation">(Leamer <a href="#ref-leamer1983" role="doc-biblioref">1983</a>)</span>, which involves fitting a random selection of possible models to the data and extracting treatment effects estimates from each one, and the Athey-Imbens procedure <span class="citation">(Athey and Imbens <a href="#ref-athey2015" role="doc-biblioref">2015</a>)</span>, which involves splitting the data across covariate boundaries and examining how variable the effect estimates are across splits. When using pair distance-based frontiers, only the extreme bounds procedure is available, so we use that below.</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mahal.MD</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/modelDependence.html">modelDependence</a></span><span class="op">(</span><span class="va">re78</span> <span class="op">~</span> <span class="va">treat</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span> 
                              <span class="va">married</span> <span class="op">+</span> <span class="va">nodegree</span> <span class="op">+</span> <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,
                            data <span class="op">=</span> <span class="va">mahal.matched.data</span>, 
                            weights <span class="op">=</span> <span class="va">mahal.matched.data</span><span class="op">$</span><span class="va">weights</span>,
                            treatment <span class="op">=</span> <span class="st">"treat"</span>,
                            method <span class="op">=</span> <span class="st">"extreme-bounds"</span>, 
                            seed <span class="op">=</span> <span class="fl">12345</span><span class="op">)</span>
<span class="va">mahal.MD</span></code></pre></div>
<pre><code>## Extreme model dependence bounds: 
##     lower     upper      diff 
## -653.9116  346.6681 1000.5796</code></pre>
<p>Here we see that had we used other model specifications, we could have found treatment effect estimates between -654 and 347, for a difference of 1001, indicating our treatment effect estimate may be somewhat sensitive to the model specification.</p>
</div>
<div id="estimating-effects-along-the-frontier" class="section level3">
<h3 class="hasAnchor">
<a href="#estimating-effects-along-the-frontier" class="anchor"></a>Estimating effects along the frontier</h3>
<p>The next step is to estimate treatment effects along the frontier. Doing so allows us to examine the sensitivity of our results to the choice of our sample size/imbalance trade-off. To estimates these effects, we use the <code>estimatEffects()</code> function. This function estimates treatment effects, confidence intervals, and, optionally, model dependence bounds at each point on the frontier. With a large frontier, this can take a long time, so we can request that only some proportion of the points along the frontier have estimates using the <code>prop.estimated</code> argument. We will request the extreme bounds procedure be used to assess model sensitivity, as we did for the single point estimate above.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mahal.estimates</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/estimateEffects.html">estimateEffects</a></span><span class="op">(</span><span class="va">mahal.frontier</span>, 
                                   base.form <span class="op">=</span> <span class="va">re78</span> <span class="op">~</span> <span class="va">treat</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span>
                                     <span class="va">race</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">nodegree</span> <span class="op">+</span> <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,
                                   prop.estimated <span class="op">=</span> <span class="fl">.5</span>,
                                   method <span class="op">=</span> <span class="st">"extreme-bounds"</span>,
                                   verbose <span class="op">=</span> <span class="cn">FALSE</span>,
                                   seed <span class="op">=</span> <span class="fl">12345</span><span class="op">)</span></code></pre></div>
<p>Printing the resulting <code>frontierEstimates</code> object provides some information about the estimation procedure.</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mahal.estimates</span></code></pre></div>
<pre><code>## A frontierEstimates object
## - quantity of interest: FSATT
## - model sensitivity method: extreme bounds
##    - number of specifications: 100
## - number of estimates: 69
## - treatment: treat
## - covariates: age, educ, race, married, nodegree, re74, re75
## - outcome model: re78 ~ treat + age + educ + race + married + nodegree + re74 + re75</code></pre>
<p>Next, we can plot the estimates across the frontier using <code><a href="../reference/plot.frontierEstimates.html">plot.frontierEstimates()</a></code>. We can choose to display the model dependence bands or confidence bands using the argument to <code>band</code>. We’ll begin by looking at model dependence.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mahal.estimates</span>, band <span class="op">=</span> <span class="st">"model-dependence"</span><span class="op">)</span></code></pre></div>
<p><img src="MatchingFrontier_files/figure-html/unnamed-chunk-16-1.png" width="672"></p>
<p>We can see that model dependence varies along the frontier, and markedly increases once 120 treated units are dropped. However, at the last point of the frontier, where the groups are perfectly balanced, model dependence drops to zero. Next, we can plot confidence bands along the frontier.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mahal.estimates</span>, band <span class="op">=</span> <span class="st">"confidence"</span><span class="op">)</span></code></pre></div>
<p><img src="MatchingFrontier_files/figure-html/unnamed-chunk-17-1.png" width="672"></p>
<p>As sample size decreases, the confidence band width increases, as expected.</p>
</div>
<div id="using-other-types-of-frontiers" class="section level3">
<h3 class="hasAnchor">
<a href="#using-other-types-of-frontiers" class="anchor"></a>Using other types of frontiers</h3>
<p>Above, we demonstrated the use of <code>MatchingFrontier</code> with a pair distance-based frontier. Other type of frontiers work slightly differently because no pairing is done, so the frontier tracks changes from a truly unadjusted sample to a fully adjusted sample, where the adjustment comes in form of discarding units. In contrast, the first step of the pair distance-based frontier tends to be better balanced than the original dataset because pairing has already been done. Below, we briefly demonstrate using an energy distance-based frontier to estimate the SATE.</p>
<p>First, we compute the frontier using <code><a href="../reference/makeFrontier.html">makeFrontier()</a></code>.</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">energy.frontier</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/makeFrontier.html">makeFrontier</a></span><span class="op">(</span><span class="va">treat</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span> 
                                  <span class="va">married</span> <span class="op">+</span> <span class="va">nodegree</span> <span class="op">+</span> <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,
                                data <span class="op">=</span> <span class="va">lalonde</span>, 
                                QOI <span class="op">=</span> <span class="st">"SATE"</span>, 
                                metric <span class="op">=</span> <span class="st">"Energy"</span><span class="op">)</span>
<span class="va">energy.frontier</span></code></pre></div>
<pre><code>## A matchFrontier object
## - quantity of interest: SATE
## - imbalance metric: energy distance
## - treatment: treat
## - covariates: age, educ, race, married, nodegree, re74, re75
## - number of points: 559</code></pre>
<p>Next, we can plot the frontier to see the relationship between sample size and imbalance. Because we are estimating the SATE, imbalance represents the difference between the distribution of the treated units, the distribution of the control units, and the distribution of the original (target) sample. Thus, as imbalance decreases, the groups look more similar to each other and to the original sample.</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">energy.frontier</span><span class="op">)</span></code></pre></div>
<p><img src="MatchingFrontier_files/figure-html/unnamed-chunk-19-1.png" width="672"></p>
<p>In contrast to pair distance-based frontiers, energy distance-based frontiers are not monotonic; there is a point at which decreasing the size of the remain sample makes balance worse, which does not occur with pair distance-based frontiers. To find the point along the frontier with the best balance, we can use <code><a href="../reference/summary.matchFrontier.html">summary.matchFrontier()</a></code>:</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">energy.frontier</span><span class="op">)</span></code></pre></div>
<pre><code>## Summary of matchFrontier object:
## 
##       N treated N control N total Statistic
## Start       185       429     614     1.895
## End          11        11      22     0.489
## Best         32       150     182     0.143
##                                 ^</code></pre>
<p>Here we can see that the balance is best when 182 units remain, though the plot indicates that it is possible to have similar balance while discarding fewer units. We can use the steps previously described to extract the dataset at that point on the frontier and estimate its treatment effect and model dependence. First we will turn that point into a <code>matchit</code> object and assess balance on the covariates.</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">energy.matchit</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/frontier_to_matchit.html">frontier_to_matchit</a></span><span class="op">(</span><span class="va">energy.frontier</span>, N <span class="op">=</span> <span class="fl">182</span><span class="op">)</span>
<span class="co">#same thing:      frontier_to_matchit(energy.frontier, Ndrop = 432)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">energy.matchit</span>, un <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## makeFrontier(formula = treat ~ age + educ + race + married + 
##     nodegree + re74 + re75, data = lalonde, QOI = "SATE", metric = "Energy")
## 
## Summary of Balance for Matched Data:
##            Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean eCDF Max
## age              26.6875       27.1200         -0.0473     0.7997    0.0266   0.0787
## educ             10.2188       10.2200         -0.0005     0.8424    0.0212   0.0596
## raceblack         0.4375        0.4067          0.0804          .    0.0308   0.0308
## racehispan        0.1250        0.1200          0.0168          .    0.0050   0.0050
## racewhite         0.4375        0.4733         -0.0905          .    0.0358   0.0358
## married           0.4062        0.4133         -0.0158          .    0.0071   0.0071
## nodegree          0.6250        0.6333         -0.0176          .    0.0083   0.0083
## re74           4544.2214     4414.5676          0.0219     1.4689    0.0370   0.2067
## re75           2453.3611     2306.8545          0.0450     1.3201    0.0439   0.1137
## 
## Sample Sizes:
##           Control Treated
## All           429     185
## Matched       150      32
## Unmatched     279     153
## Discarded       0       0</code></pre>
<p>We can see that mean difference are very low in the extracted sample, indicating good balance. We can move forward with effect estimation and assessing model dependence after extracting the matched dataset.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">energy.matched.data</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/generateDataset.html">generateDataset</a></span><span class="op">(</span><span class="va">energy.frontier</span>, N <span class="op">=</span> <span class="fl">182</span><span class="op">)</span>
<span class="co">#Same result:          MatchIt::match.data(energy.matchit, data = lalonde)</span></code></pre></div>
<p>Because no pairing has taken place, we don’t need to worry about replicating units in the dataset, so we don’t have to set <code>dup = TRUE</code> and our output is the same as had we used <code><a href="https://kosukeimai.github.io/MatchIt/reference/match.data.html">match.data()</a></code> on the <code>matchit</code> object.</p>
<p>Below, we estimate the SATE using regression as we did before (note the weights are unnecessary here but it’s good practice to use them):</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># library("lmtest") #already loaded</span>
<span class="co"># library("sandwich")</span>

<span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">re78</span> <span class="op">~</span> <span class="va">treat</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> 
            <span class="va">nodegree</span> <span class="op">+</span> <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,
          data <span class="op">=</span> <span class="va">energy.matched.data</span>, weights <span class="op">=</span> <span class="va">weights</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/coeftest.html">coeftest</a></span><span class="op">(</span><span class="va">fit</span>, vcov. <span class="op">=</span> <span class="va">vcovHC</span><span class="op">)</span><span class="op">[</span><span class="st">"treat"</span>,, drop <span class="op">=</span> <span class="cn">FALSE</span><span class="op">]</span></code></pre></div>
<pre><code>##       Estimate Std. Error   t value Pr(&gt;|t|)
## treat  701.262   1504.433 0.4661304 0.641712</code></pre>
<p>We can assess model dependence using <code><a href="../reference/modelDependence.html">modelDependence()</a></code>. Because we are not using a pair distance-based frontier, we can use the Athey-Imbens model dependence procedure in addition to the extreme bounds procedure. We’ll do so below.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">energy.MD</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/modelDependence.html">modelDependence</a></span><span class="op">(</span><span class="va">re78</span> <span class="op">~</span> <span class="va">treat</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span>
                               <span class="va">married</span> <span class="op">+</span> <span class="va">nodegree</span> <span class="op">+</span> <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,
                             data <span class="op">=</span> <span class="va">energy.matched.data</span>,
                             weights <span class="op">=</span> <span class="va">energy.matched.data</span><span class="op">$</span><span class="va">weights</span>,
                             treatment <span class="op">=</span> <span class="st">"treat"</span>,
                             method <span class="op">=</span> <span class="st">"athey-imbens"</span>,
                             cutpoint.method <span class="op">=</span> <span class="st">"mean"</span><span class="op">)</span>
<span class="va">energy.MD</span></code></pre></div>
<pre><code>## Athey-Imbens model dependence bounds: 
##      lower      upper       diff 
##   93.85873 1308.66520 1214.80648</code></pre>
<p>Next, we will estimate effects and model dependence bounds across the frontier.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">energy.estimates</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/estimateEffects.html">estimateEffects</a></span><span class="op">(</span><span class="va">energy.frontier</span>, 
                                    base.form <span class="op">=</span> <span class="va">re78</span> <span class="op">~</span> <span class="va">treat</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span>
                                      <span class="va">educ</span> <span class="op">+</span> <span class="va">race</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">nodegree</span> <span class="op">+</span> <span class="va">re74</span> <span class="op">+</span> <span class="va">re75</span>,
                                    prop.estimated <span class="op">=</span> <span class="fl">.5</span>,
                                    method <span class="op">=</span> <span class="st">"athey-imbens"</span>, 
                                    cutpoint.method <span class="op">=</span> <span class="st">"mean"</span>,
                                    verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">energy.estimates</span></code></pre></div>
<pre><code>## A frontierEstimates object
## - quantity of interest: SATE
## - model sensitivity method: Athey-Imbens
##    - cutpoint method: mean
## - number of estimates: 280
## - treatment: treat
## - covariates: age, educ, race, married, nodegree, re74, re75
## - outcome model: re78 ~ treat + age + educ + race + married + nodegree + re74 + re75</code></pre>
<p>It’s important to remember that with frontiers other than pair distance-based frontiers, the effects estimated at the beginning of the frontier may be biased because no matching has been performed. Only toward the frontier’s trough should estimates be interpreted as potentially valid as these have been adjusted through dropping units to improve balance. We’ll plot the estimates and their model dependence below:</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">energy.estimates</span>, band <span class="op">=</span> <span class="st">"model-dependence"</span><span class="op">)</span></code></pre></div>
<p><img src="MatchingFrontier_files/figure-html/unnamed-chunk-26-1.png" width="672"></p>
<p>Next we’ll plot the estimates and their confidence intervals:</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">energy.estimates</span>, band <span class="op">=</span> <span class="st">"confidence"</span><span class="op">)</span></code></pre></div>
<p><img src="MatchingFrontier_files/figure-html/unnamed-chunk-27-1.png" width="672"></p>
<p>Remember that we targeted two different quantities of interest with the Mahalanobis distance frontier and the energy distance frontier, so we should not expect estimates to exactly coincide.</p>
</div>
</div>
<div id="conclusion" class="section level2">
<h2 class="hasAnchor">
<a href="#conclusion" class="anchor"></a>Conclusion</h2>
<p><code>MatchingFrontier</code> provides a user-friendly interface to assessing the balance-sample size frontier in matching for observational studies. By using the tools presented here, users can estimate effects in an optimal way (given the choice of imbalance metric and estimand) and be honest about the dependence of their results on their modeling choices. By interfacing directly with <code>MatchIt</code>, <code>MatchingFrontier</code> connects the two packages so that users can take advantage of the assessment and plotting tools <code>MatchIt</code> has to offer.</p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-athey2015">
<p>Athey, Susan, and Guido Imbens. 2015. “A Measure of Robustness to Misspecification.” <em>American Economic Review</em> 105 (5): 476–80. <a href="https://doi.org/10.1257/aer.p20151020">https://doi.org/10.1257/aer.p20151020</a>.</p>
</div>
<div id="ref-greifer2021">
<p>Greifer, Noah, and Elizabeth A. Stuart. 2021. “Choosing the Estimand When Matching or Weighting in Observational Studies.” <em>arXiv:2106.10577 [Stat]</em>, June. <a href="http://arxiv.org/abs/2106.10577">http://arxiv.org/abs/2106.10577</a>.</p>
</div>
<div id="ref-hill2006">
<p>Hill, Jennifer, and Jerome P. Reiter. 2006. “Interval Estimation for Treatment Effects Using Propensity Score Matching.” <em>Statistics in Medicine</em> 25 (13): 2230–56. <a href="https://doi.org/10.1002/sim.2277">https://doi.org/10.1002/sim.2277</a>.</p>
</div>
<div id="ref-hlavac2016">
<p>Hlavac, Marek. 2016. “ExtremeBounds: Extreme Bounds Analysis in R.” <em>Journal of Statistical Software</em> 72 (9). <a href="https://doi.org/10.18637/jss.v072.i09">https://doi.org/10.18637/jss.v072.i09</a>.</p>
</div>
<div id="ref-JSSv042i08">
<p>Ho, Daniel E., Kosuke Imai, Gary King, and Elizabeth A. Stuart. 2011. “MatchIt: Nonparametric Preprocessing for Parametric Causal Inference.” <em>Journal of Statistical Software, Articles</em> 42 (8): 128. <a href="https://doi.org/10.18637/jss.v042.i08">https://doi.org/10.18637/jss.v042.i08</a>.</p>
</div>
<div id="ref-huling2020">
<p>Huling, Jared D., and Simon Mak. 2020. “Energy Balancing of Covariate Distributions.” <em>arXiv:2004.13962 [Stat]</em>, December. <a href="http://arxiv.org/abs/2004.13962">http://arxiv.org/abs/2004.13962</a>.</p>
</div>
<div id="ref-iacus2012">
<p>Iacus, Stefano M., Gary King, and Giuseppe Porro. 2012. “Causal Inference Without Balance Checking: Coarsened Exact Matching.” <em>Political Analysis</em> 20 (1): 1–24. <a href="https://doi.org/10.1093/pan/mpr013">https://doi.org/10.1093/pan/mpr013</a>.</p>
</div>
<div id="ref-iacus2011">
<p>———. 2011. “Multivariate Matching Methods That Are Monotonic Imbalance Bounding.” <em>Journal of the American Statistical Association</em> 106 (493): 345–61. <a href="https://doi.org/10.1198/jasa.2011.tm09599">https://doi.org/10.1198/jasa.2011.tm09599</a>.</p>
</div>
<div id="ref-iacus2019">
<p>———. 2019. “A Theory of Statistical Inference for Matching Methods in Causal Research.” <em>Political Analysis</em> 27 (1): 46–68. <a href="https://doi.org/10.1017/pan.2018.29">https://doi.org/10.1017/pan.2018.29</a>.</p>
</div>
<div id="ref-king2017">
<p>King, Gary, Christopher Lucas, and Richard A. Nielsen. 2017. “The Balance-Sample Size Frontier in Matching Methods for Causal Inference.” <em>American Journal of Political Science</em> 61 (2): 473–89. <a href="https://doi.org/10.1111/ajps.12272">https://doi.org/10.1111/ajps.12272</a>.</p>
</div>
<div id="ref-king2019">
<p>King, Gary, and Richard Nielsen. 2019. “Why Propensity Scores Should Not Be Used for Matching.” <em>Political Analysis</em>, May, 1–20. <a href="https://doi.org/10.1017/pan.2019.11">https://doi.org/10.1017/pan.2019.11</a>.</p>
</div>
<div id="ref-lalonde1986">
<p>LaLonde, Robert J. 1986. “Evaluating the Econometric Evaluations of Training Programs with Experimental Data.” <em>The American Economic Review</em> 76 (4): 604–20. <a href="http://www.jstor.org/stable/1806062">http://www.jstor.org/stable/1806062</a>.</p>
</div>
<div id="ref-leamer1983">
<p>Leamer, Edward E. 1983. “Let’s Take the Con Out of Econometrics.” <em>The American Economic Review</em> 73 (1): 31–43. <a href="http://www.jstor.org/stable/1803924">http://www.jstor.org/stable/1803924</a>.</p>
</div>
<div id="ref-rizzo2016">
<p>Rizzo, Maria L., and Gábor J. Székely. 2016. “Energy Distance.” <em>WIREs Computational Statistics</em> 8 (1): 27–38. <a href="https://doi.org/https://doi.org/10.1002/wics.1375">https://doi.org/https://doi.org/10.1002/wics.1375</a>.</p>
</div>
<div id="ref-rosenbaum2020">
<p>Rosenbaum, Paul R. 2020. “Modern Algorithms for Matching in Observational Studies.” <em>Annual Review of Statistics and Its Application</em> 7 (1): 143–76. <a href="https://doi.org/10.1146/annurev-statistics-031219-041058">https://doi.org/10.1146/annurev-statistics-031219-041058</a>.</p>
</div>
<div id="ref-stuart2010">
<p>Stuart, Elizabeth A. 2010. “Matching Methods for Causal Inference: A Review and a Look Forward.” <em>Statistical Science</em> 25 (1): 1–21. <a href="https://doi.org/10.1214/09-STS313">https://doi.org/10.1214/09-STS313</a>.</p>
</div>
<div id="ref-székely2013">
<p>Székely, Gábor J., and Maria L. Rizzo. 2013. “Energy Statistics: A Class of Statistics Based on Distances.” <em>Journal of Statistical Planning and Inference</em> 143 (8): 1249–72. <a href="https://doi.org/10.1016/j.jspi.2013.03.018">https://doi.org/10.1016/j.jspi.2013.03.018</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Gary King, Christopher Lucas, Richard Nielsen, Noah Greifer.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
